
spring:
  security:
    user:
      password: password
  datasource:
    password: password123!
    url: jdbc:mysql://localhost:3306/scrumr
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true



